server:
  port: 8080

#spring配置
spring:
  #druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minimap?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 3
    minIdle: 3
    maxActive: 10
    maxWait: 6000
  #mvc配置
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#mybatis配置，mapper映射
mybatis:
  mapper-locations: classpath:com/minimap/mapper/*.xml
  type-aliases-package: com.minimap.pojo

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.242.131:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5
logging:
  config: classpath:logback-spring.xml
  debug: true
